Further update of the script v2

diff --git a/.github/workflows/ci-web.yml b/.github/workflows/ci-web.yml
--- a/.github/workflows/ci-web.yml
+++ b/.github/workflows/ci-web.yml
@@ -6,75 +6,78 @@ on:
             - main
     pull_request: {}
 
-# jobs:
-#     test:
-#         timeout-minutes: 60
-#         runs-on: ubuntu-latest
-#         steps:
-#             - uses: actions/checkout@v4
-#             - uses: actions/setup-node@v4
-#               with:
-#                   node-version: 18
-#             - name: Install dependencies
-#               run: npm ci
-#             - name: Install Playwright Browsers
-#               run: npx playwright install --with-deps
-#             - name: Run Playwright tests
-#               run: npx playwright test
-#             - uses: actions/upload-artifact@v4
-#               if: ${{ !cancelled() }}
-#               with:
-#                   name: playwright-report
-#                   path: playwright-report/
-#                   retention-days: 30
 jobs:
     test:
+        timeout-minutes: 60
         runs-on: ubuntu-latest
-
-        services:
-            # Setup a service to run the Next.js app
-            web:
-                image: node:16
-                ports:
-                    - 3000:3000
-                options: >-
-                    --health-cmd="curl --fail http://localhost:3000 || exit 1"
-                    --health-interval=10s
-                    --health-timeout=5s
-                    --health-retries=3
-
         steps:
             - name: Checkout repository
-              uses: actions/checkout@v2
+              uses: actions/checkout@v4
 
-            - name: Set up Node.js
-              uses: actions/setup-node@v2
+            - name: Set up Node
+              uses: actions/setup-node@v4
               with:
-                  node-version: '16'
-
-            - name: Install pnpm
-              run: npm install -g pnpm
-
+                  node-version: 18
             - name: Install dependencies
-              run: pnpm install
-
-            - name: Build the application
-              run: pnpm run build
-
-            - name: Start the application
-              run: pnpm run start &
-              env:
-                  PORT: 3000
-
-            - name: Wait for the app to be ready
-              run: sleep 10 # Adjust this value if your app takes longer to start
-
+              run: npm ci
+            - name: Install Playwright Browsers
+              run: npx playwright install --with-deps
             - name: Run Playwright tests
-              run: pnpm exec playwright test
-
-            - name: Upload Playwright test results
-              if: always()
-              uses: actions/upload-artifact@v2
+              run: npx playwright test
+            - uses: actions/upload-artifact@v4
+              if: ${{ !cancelled() }}
               with:
-                  name: playwright-results
-                  path: playwright-report
+                  name: playwright-report
+                  path: playwright-report/
+                  retention-days: 30
+# jobs:
+#     test:
+#         runs-on: ubuntu-latest
+
+#         services:
+#             # Setup a service to run the Next.js app
+#             web:
+#                 image: node:16
+#                 ports:
+#                     - 3000:3000
+#                 options: >-
+#                     --health-cmd="curl --fail http://localhost:3000 || exit 1"
+#                     --health-interval=10s
+#                     --health-timeout=5s
+#                     --health-retries=3
+
+#         steps:
+#             - name: Checkout repository
+#               uses: actions/checkout@v2
+
+#             - name: Set up Node.js
+#               uses: actions/setup-node@v2
+#               with:
+#                   node-version: '16'
+
+#             - name: Install pnpm
+#               run: npm install -g pnpm
+
+#             - name: Install dependencies
+#               run: pnpm install
+
+#             - name: Build the application
+#               run: pnpm run build
+
+#             - name: Start the application
+#               run: pnpm run start &
+#               env:
+#                   PORT: 3000
+
+#             - name: Wait for the app to be ready
+#               run: sleep 10 # Adjust this value if your app takes longer to start
+
+#             - name: Run Playwright tests
+#               run: pnpm exec playwright test
+
+#             - name: Upload Playwright test results
+#               if: always()
+#               uses: actions/upload-artifact@v2
+#               with:
+#                   name: playwright-results
+#                   path: playwright-report
